name: charts_common_sa
version: 0.13.1
description: A common library for charting packages.
homepage: https://github.com/shahzebnaqvi/Charts_SN
platforms:
  android:
  ios:
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  collection: ^1.18.0
  intl: ^0.18.0
  logging: ^1.2.0
  meta: ^1.1.1
  vector_math: ^2.1.4

dev_dependencies:
  mockito: ^5.4.3
  test: ^1.24.9
