name: charts_flutter_sa
version: 0.1.2
description: Material Design charting library for flutter.
homepage: https://github.com/shahzebnaqvi/Charts_SN

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter_sa will point to the pub version of charts_common_sa.
  # The latest pub version is commented out and shown below as an example.
  charts_common_sa: ^0.13.1
  # charts_common_sa:
  #   path: ../charts_common_sa/
  collection: ^1.18.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  logging: ^1.2.0
  meta: ^1.10.0


dev_dependencies:
  mockito: ^5.0.0
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  test: ^1.3.0
